# Generated by Django 5.0 on 2023-12-18 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_block_is_active_science_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckTestAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.science')),
            ],
        ),
    ]
