# Generated by Django 5.0.1 on 2024-01-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_science_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='name',
        ),
        migrations.RemoveField(
            model_name='block',
            name='size',
        ),
    ]
