# Generated by Django 5.0.1 on 2024-02-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerblock',
            name='false_answers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='answerblock',
            name='true_answers',
            field=models.JSONField(),
        ),
    ]
