# Generated by Django 5.0.1 on 2024-01-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerscience',
            name='false_answers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answerscience',
            name='true_answers',
            field=models.IntegerField(),
        ),
    ]
