# Generated by Django 5.0.1 on 2024-01-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_answerblock_created_at_answerscience_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='science',
            name='size',
        ),
        migrations.AlterField(
            model_name='science',
            name='keys',
            field=models.JSONField(),
        ),
    ]
