# Generated by Django 5.0.1 on 2024-02-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='keys',
            field=models.JSONField(),
        ),
    ]
